name: Deploy to production
on:
  push:
    branches:
      - PROD
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install App Dependecy
        run: npm install
      - name: Build de APP Deploy
        run: npm run deploy